name: goub
suffix: ~  # add suffix to saved images
model: denoising
distortion: derain
gpu_ids: [0]

sde:
  lambda_square: 30
  T: 100
  schedule: cosine # linear, cosine
  eps: 0.005
  
degradation:
  # for super-resolution
  scale: 4

datasets:
  test1:
    name: Val_Dataset
    mode: LQGT
    dataroot_GT: C:/datasets/LOL-v1/eval15/high
    dataroot_LQ: C:/datasets/LOL-v1/eval15/low


network_G:
  which_model_G: ConditionalNAFNet
  setting:
    width: 64
    enc_blk_nums: [1, 1, 1, 28]
    middle_blk_num: 1
    dec_blk_nums: [1, 1, 1, 1]

#### path
path:
  pretrain_model_G: C:/Users/朱禹溪/Desktop/lolv1.pth
